CREATE TABLE IF NOT EXISTS track_metadata (
    track_id INTEGER PRIMARY KEY,
    apple_music_song_url TEXT NULL,
    apple_music_album_url TEXT NULL,
    apple_music_artist_url TEXT NULL,
    catalog_song_id TEXT NULL,
    catalog_album_id TEXT NULL,
    catalog_artist_id TEXT NULL,
    itunes_track_id INTEGER NULL,
    itunes_collection_id INTEGER NULL,
    itunes_artist_id INTEGER NULL,
    duration_seconds INTEGER NULL,
    release_date_utc TEXT NULL,
    composer_name TEXT NULL,
    genre_names_json TEXT NULL,
    track_number INTEGER NULL,
    track_count INTEGER NULL,
    disc_number INTEGER NULL,
    disc_count INTEGER NULL,
    isrc TEXT NULL,
    preview_url TEXT NULL,
    content_rating TEXT NULL,
    catalog_audio_variants_json TEXT NULL,
    artwork_url TEXT NULL,
    artwork_width INTEGER NULL,
    artwork_height INTEGER NULL,
    artwork_cache_relative_path TEXT NULL,
    storefront TEXT NULL,
    metadata_sources_json TEXT NULL,
    web_payload_json TEXT NULL,
    itunes_payload_json TEXT NULL,
    catalog_payload_json TEXT NULL,
    enriched_at_utc TEXT NOT NULL,
    artwork_cached_at_utc TEXT NULL,
    FOREIGN KEY(track_id) REFERENCES tracks(track_id)
);

CREATE INDEX IF NOT EXISTS ix_track_metadata_catalog_song_id ON track_metadata(catalog_song_id);
