using AppleMusicHistory.Core.Models;

namespace AppleMusicHistory.Host;

public sealed record DashboardState(
    bool IsTrackingPaused,
    bool LaunchAtStartup,
    bool MetadataEnrichmentEnabled,
    string TrackerStatus,
    string AppleMusicState,
    string CurrentTrack,
    string CurrentTitle,
    string CurrentArtist,
    string CurrentAlbum,
    string CurrentComposer,
    string CurrentReleaseDate,
    string CurrentGenres,
    string CurrentTrackNumbers,
    string CurrentIsrc,
    string CurrentSongUrl,
    string CurrentAlbumUrl,
    string CurrentArtistUrl,
    string CurrentArtworkPathOrUrl,
    string ActiveSession,
    string Statistics,
    string LastObserved,
    string DatabasePath,
    string CurrentAudioFormat,
    PlaybackAudioVariant? CurrentAudioVariant,
    string SourceDiagnosticMessage,
    int? CurrentPositionSeconds,
    int? DurationSeconds,
    double PlaybackProgress,
    string ElapsedText,
    string RemainingText,
    string PaletteSeed)
{
    public static DashboardState CreateDefault(string databasePath, bool launchAtStartup, bool metadataEnrichmentEnabled, bool isTrackingPaused)
        => new(
            isTrackingPaused,
            launchAtStartup,
            metadataEnrichmentEnabled,
            isTrackingPaused ? "Tracking paused" : "Tracking active",
            "Starting Apple Music tracker",
            "No current track",
            "No current track",
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            "No active session",
            "Tracks: 0 | Sessions: 0 | Open: 0",
            "Never",
            databasePath,
            "Standard / unknown",
            PlaybackAudioVariant.Unknown,
            string.Empty,
            null,
            null,
            0,
            "0:00",
            "-0:00",
            databasePath);
}
